language: objective-c
osx_image: beta-xcode6.3

branches:
  only:
    - master

before_install:
  - brew update
  - brew install carthage
  - gem install xcpretty
  - carthage bootstrap --use-ssh --configuration Debug --platform Mac

before_script:
  - set -o pipefail

script:
  - xcodebuild build test -project TBCCore.xcodeproj -scheme TBCCore-mac.framework -sdk macosx | xcpretty
