steps:

  - name: "mac - Xcode7 - Analyze"
    command: scripts/ci-staticlib-analyze
    agents:
      os: macos
      queue: mobile
      xcode: 7.3
    env:
      XCODE_SCHEME: TBCCore-mac
      XCODE_SDK: macosx

  - name: "mac - Xcode7 - Test"
    command: scripts/ci-staticlib-test
    agents:
      os: macos
      queue: mobile
      xcode: 7.3
    env:
      XCODE_SCHEME: TBCCore-mac
      XCODE_SDK: macosx

  - name: "mac - Xcode8 - Analyze"
    command: scripts/ci-staticlib-analyze
    agents:
      os: macos
      queue: mobile
      xcode: 8
    env:
      XCODE_SCHEME: TBCCore-mac
      XCODE_SDK: macosx

  - name: "mac - Xcode8 - Test"
    command: scripts/ci-staticlib-test
    agents:
      os: macos
      queue: mobile
      xcode: 8
    env:
      XCODE_SCHEME: TBCCore-mac
      XCODE_SDK: macosx

  - name: "iOS - Xcode7 - Analyze"
    command: scripts/ci-staticlib-analyze
    agents:
      os: macos
      queue: mobile
      xcode: 7.3
    env:
      XCODE_SCHEME: TBCCore-iOS
      XCODE_SDK: iphonesimulator
      XCODE_DESTINATION: "platform=iOS Simulator,name=iPhone 6"

  - name: "iOS - Xcode7 - Test"
    command: scripts/ci-staticlib-test
    agents:
      os: macos
      queue: mobile
      xcode: 7.3
    env:
      XCODE_SCHEME: TBCCore-iOS
      XCODE_SDK: iphonesimulator
      XCODE_DESTINATION: "platform=iOS Simulator,name=iPhone 6"

  - name: "iOS - Xcode8 - Analyze"
    command: scripts/ci-staticlib-analyze
    agents:
      os: macos
      queue: mobile
      xcode: 8
    env:
      XCODE_SCHEME: TBCCore-iOS
      XCODE_SDK: iphonesimulator
      XCODE_DESTINATION: "platform=iOS Simulator,name=iPhone 6"


  - name: "iOS - Xcode8 - Test"
    command: scripts/ci-staticlib-test
    agents:
      os: macos
      queue: mobile
      xcode: 8
    env:
      XCODE_SCHEME: TBCCore-iOS
      XCODE_SDK: iphonesimulator
      XCODE_DESTINATION: "platform=iOS Simulator,name=iPhone 6"

  - name: "iOS Example"
    command: scripts/ci-build-example
    agents:
      os: macos
      queue: mobile
      xcode: 7.3
    env:
      XCODE_SCHEME: TBCCoreExample-iOS
      XCODE_SDK: iphonesimulator
