steps:

  - name: "mac"
    command: scripts/cibuild
    agents:
      os: macos
      queue: mobile
      xcode: 7.3
    env:
      XCODE_SCHEME: TBCCore-mac
      XCODE_SDK: macosx

  - name: "iOS"
    command: scripts/cibuild
    agents:
      os: macos
      queue: mobile
      xcode: 7.3
    env:
      XCODE_SCHEME: TBCCore-iOS
      XCODE_SDK: iphonesimulator

  - name: "iOS Example"
    command: scripts/cibuild
    agents:
      os: macos
      queue: mobile
      xcode: 7.3
    env:
      XCODE_SCHEME: TBCCoreExample-iOS
      XCODE_SDK: iphonesimulator
